# Generated by Django 4.0.8 on 2022-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('birth', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('death', models.CharField(blank=True, max_length=200)),
                ('hair', models.CharField(blank=True, max_length=200)),
                ('height', models.CharField(blank=True, max_length=200)),
                ('realm', models.CharField(blank=True, max_length=200)),
                ('spouse', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
